# -*- coding: utf-8 -*-
"""Image to Pencil Sketch App

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8PjWBb4nqxYvs3WrrQsY18gyxKq_nGD
"""

import cv2
import numpy as np
from google.colab import files
from IPython.display import display
import ipywidgets as widgets
from IPython.display import display

upload = widgets.FileUpload()
display(upload)

def on_upload_change(change):
    if upload.data:
        img = cv2.imdecode(np.frombuffer(upload.data[0], np.uint8), -1)
        sketch = create_pencil_sketch(img)
        cv2.imwrite('746.jpg', sketch)
        display(widgets.Image(value=open('746.jpg', 'rb').read()))

upload.observe(on_upload_change, names='_counter')

def create_pencil_sketch(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    inverted_gray = cv2.bitwise_not(gray)
    blurred = cv2.GaussianBlur(inverted_gray, (21, 21), sigmaX=0, sigmaY=0)
    pencil_sketch = cv2.divide(255, blurred, scale=256)
    return pencil_sketch

display(upload)

